:doctype: book
:stylesheet: ../../cctc.css

= Activity - Modify Audit Policy
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Learning Objectives / Outcomes

* CCWI004: Develop scripts
* CCWI013: Explain the purpose of Windows Registry
* CCWI014.002: Use command line syntax to query, view, analyze, modify and create Registry values
* CCWI014.003: Explain when and how changes to the Registry are expected to take effect
* CCWI016: Identify basic Windows firewall concepts 
* CCWI031.003: Discuss the differences between malicious and normal activity
* CCWI022: Define Windows auditing

{empty} +

== Scenario

You have exploited onto a Windows Endpoint machine. To avoid having to re-exploit in the future,
You want to modify the Windows Firewall policy to allow for external telnet access.
You must verify if your actions left logs and if you have achieved the desired effect.

{empty} +

== Setup

Conduct this activity on your Windows 7 or 10 machine. Prepare the system by completing the following:

* Go to Control Panel -> System and Security -> Windows Firewall -> Advanced Settings -> Inbound Rules -> New Rule -> Port -> Next -> TCP 23 -> Next -> Block the Connection -> Next -> Name: TELNET
* In an administrative Command Prompt run the following command: `auditpol.exe /set /category:* /success:enable /failure:enable`

{empty} +

== Activity
Write a PowerShell script to allow telnet access through the Windows Firewall, and retrieve the firewall logs for today's date.

=== Task 1)
Write a PowerShell script to modify the Windows firewall to allow TELNET traffic by command-line/PowerShell modification of the Windows Registry.

=== Task 2)
Extend your script to modify the audit policy to disable credential validation.

=== Task 3)
Have your script retrieve the firewall logs for today's date.

{empty} +

== Deliverables

* Your script
* The output / screenshot of your script indicating Step 2 and 3 were successful
* Screenshot of Windows Firewall GUI, proving that the changes took effect
* Documented analysis of Windows logging behavior with regards to Windows Firewall modifications

{empty} +

== Grading
* 70% - Script that runs, edits audit policy and retrieves logs
* +20% - Successfully modified Windows firewall through the registry
* +10% - Correct, clear and concise analysis of Windows Firewall logging behavior

{empty} +

== Hints
N/A

{empty} +

== Challenge
N/A

{empty} +

== Useful Resources
"Windows Firewall with Advanced Security Administration with Windows PowerShell," Microsoft Corporation. https://technet.microsoft.com/en-us/library/hh831755(v=ws.11).aspx
