:doctype: book
:stylesheet: ../../cctc.css

= Activity - Modify Audit Policy
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Learning Objectives / Outcomes

* Familiarity with Registry Modification, Windows firewall, and auditing
* Researching Windows PowerShell cmdlets and advanced command line applications
* Assessing security and operational implications of audit policy modifications
* Presenting analysis in a clear and concise manner

{empty} +

== Scenario

You have access to a Windows system through a PowerShell session, but you do not have GUI access.
You are running a false flag operation and want to make it look like you are a low-level hacker.
You want to modify the Windows Firewall policy to allow for external telnet access.
You must verify if your actions left logs and if you have achieved the desired effect.

{empty} +

== Setup

Conduct this activity on your Windows 7 machine. Prepare the system by completing the following:

* Go to Control Panel -> System and Security -> Windows Firewall -> Advanced Settings -> Inbound Rules -> New Rule -> Port -> Next -> TCP 23 -> Next -> Block the Connection -> Next -> Name: TELNET
* In an administrative Command Prompt run the following command: `auditpol.exe /set /category:* /success:enable /failure:enable`

{empty} +

== Activity
Write a PowerShell script to make it look like you are a low-level hacker.

=== Task 1)
Write a PowerShell script to modify the Windows firewall to allow TELNET traffic by command-line/PowerShell modification of the Windows Registry.

=== Task 2)
Extend your script to modify the audit policy to disable credential validation.

=== Task 3)
Have your script retrieve the firewall logs for today's date.

{empty} +

== Deliverables

* Your script
* The output / screenshot of your script indicating Step 2 and 3 were successful
* Screenshot of Windows Firewall GUI, proving that the changes took effect
* Documented analysis of Windows logging behavior with regards to Windows Firewall modifications

{empty} +

== Grading

I am uncertain if we should make this a graded exercise. The grading standard seems too fuzzy.

* 70% - Script that runs, edits audit policy and retrieves logs
* +20% - Successfully modified Windows firewall through the registry
* +10% - Clear and concise analysis of Windows Firewall logging behavior

{empty} +

== Hints
N/A
