:doctype: book
:stylesheet: ../../cctc.css

= Activity - Modify Audit Policy

== Learning Objectives

* CCWI000 - 
** CCWI000.000 - 

== Learning Outcomes

* Familiarity with Registry Modification, Windows firewall, and auditing
* Researching Windows PowerShell cmdlets and advanced command line applications
* Assessing security and operational implications of audit policy modifications
* Presenting analysis in a clear and concise manner

== Scenario

* You have access to a Windows system through a PowerShell session, but you do not have GUI access. You are running a false flag operation and want to make it look like you are a low-level hacker. You want to modify the Windows Firewall policy to allow for external telnet access. You must verify if your actions left logs and if you have achieved the desired effect.
* Conduct this activity on your Windows 7 machine. Prepare the system by completing the following:

** Go to Control Panel -> System and Security -> Windows Firewall -> Advanced Settings -> Inbound Rules -> New Rule -> Port -> Next -> TCP 23 -> Next -> Block the Connection -> Next -> Name: TELNET
** In an administrative Command Prompt run the following command: `auditpol.exe /set /category:* /success:enable /failure:enable`

=== Task 1)

* Write a PowerShell script to do the following:

** Step 1: Modify the Windows firewall to allow TELNET traffic by command-line/PowerShell modification of the Windows Registry
** Step 2: Modify the audit policy to disable credential validation
** Step 3: Retrieve the firewall event logs for today's date

== Deliverables

* Your script
* The output / screenshot of your script indicating Step 2 and 3 were successful
* Screenshot of Windows Firewall GUI, proving that the changes took effect
* Documented analysis of Windows logging behavior with regards to Windows Firewall modifications

== Hints

* N/A

== Challenge

* N/A

== Useful Resources

* N/A