:doctype: book
:stylesheet: ../../cctc.css

= Activity - Mapping a Network

== Learning Objectives

* CCNE003 - Perform network discovery
** CCNE003.001 - Analyze router configurations and create a network map

== Scenario

* You have been tasked with assisting in a network security audit for several interconnected, local, municipal facilities. Your team has been provided with a router configuration file obtained from an improperly secured FTP server during reconnaissance. In addition to starting your network diagram, you should look at the configurations critically, noting any possible security vulnerabilities.

----
GROVETOWN_PD#show run
Building configuration...
Current configuration : 5297 bytes
!
! Last configuration change at 12:52:44 UTC Fri Oct 21 1972
!
version 15.4
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname GROVETOWN_PD
!
boot-start-marker
boot-end-marker
!
no aaa new-model
!
ip domain name GROVETOWN.PD.GOV
ip cef
no ipv6 cef
multilink bundle-name authenticated
!
cts logging verbose
!
license udi pid CISCO2901/K9 sn FJC1936A1SQ
!
enable password CCTCpassword
!
username ADMINISTRATOR privilege 15 password 0 PASSWORD
!
interface Embedded-Service-Engine0/0
 no ip address
 shutdown
!
interface GigabitEthernet0/0
 ip address 10.0.1.2 255.255.254.0
 no ip redirects
 no ip proxy-arp
 standby 10 ip 10.0.1.3
 ip ospf 100 area 0
 duplex auto
 speed auto
!
interface GigabitEthernet0/1
 ip address 10.0.2.1 255.255.255.0
 ip redirects
 ip proxy-arp
 duplex auto
 speed auto
!
interface Serial0/0/0
 no ip address
 shutdown
 clock rate 2000000
!
interface Serial0/0/1
 no ip address
 shutdown
 clock rate 2000000
!
router eigrp 100
 network 10.0.2.0 0.0.0.255
 redistribute ospf 100 match external 1 external 2 metric 10000000 100 255 255 1500
!
router ospf 100
 router-id 10.0.1.2
!
ip forward-protocol nd
!
ip http server
no ip http secure-server
!
snmp-server community PUBLIC RO
snmp-server community PRIVATE RW
snmp-server host 10.0.1.199 version 2c PRIVATE
snmp-server host 10.0.1.199 version 2c PUBLIC
!
control-plane
!
banner motd ^CAuthorized access only^C
!
line con 0
!
line aux 0
!
line 2
 no activation-character
 no exec
 transport preferred none
 transport output pad telnet rlogin lapb-ta mop udptn v120 ssh
 stopbits 1
!
line vty 0 4
 login local
 transport input telnet ssh
!
line vty 5 15
 login local
 transport input telnet ssh
!
scheduler allocate 20000 1000
ntp server comcast.net
!
end

----

=== Task 1)

* In the Blackboard Activity. You will identify each item in this configuration file that you determine could be a configuration vulnerability to this router.



== Deliverables

* A powerpoint or similar graphic representation of the network with appropriate labels for significant information
* A list of at least (7) vulnerabilities noted for the device analyzed
* Recommendations to mitigate the listed vulnerabilities (commands would be helpful where applicable)

== Hints

* N/A

== Challenge

* N/A

== Useful Resources

* N/A
