:doctype: book
:stylesheet: ../../cctc.css

= Activity - SysInternals Process Tools

== Learning Objectives

* CCWI000 - 
** CCWI000.000 - 

== Learning Outcomes

* Familiarity with SysInternals Suite tools
* Capability to apply SysInternals tools achieve specific tasks
* Confidence manipulating processes and services on local and remote systems

== Scenario

* Download the SysInternals Suite to your Windows system from TechNet
* Run the following SysInternals tools to get familiar with their functionality:

** Process Explorer
** Process Monitor
** PsList
** PsKill
** PsSuspend
** PsService
** ListDLLs

=== Task 1)

* Complete the following and document the tool and process used to compete the task:

** Launch Notepad, create a new txt document and save it to the desktop. With Notepad still open, identify the file that is open (presuming you do not already know). 
** Force kill the active running instance of Notepad.
** Identify all the registry entries that are accessed, edited, and created when launching Notepad and accessing a single .txt file.
** Launch Notepad on your Windows 7 system. Query the processes running on your Windows 7 system from your Windows 10 system. Kill Notepad on your Windows 7 system from your Windows 10 system.
** Launch Notepad on your Windows 7 system. Suspend the Notepad process from your Windows 10 machine.
** Query the services running on your Windows 7 system from your Windows 10 system. Stop the Windows Defender service on Windows 7 from Windows 10. Verify that the service was stopped in Windows 7. Restart the service from Windows 10.

== Deliverables

* A document summarizing your process used to accomplish the tasks

== Hints

* N/A

== Challenge

* N/A

== Useful Resources

* N/A