docker:
  tags: 
    - docker
  image: debian:stable
  script:
      - apt-get update
      - apt-get install -y ruby wget
      - gem install rouge
      - gem install concurrent-ruby
      - gem install asciidoctor-pdf --pre
      - wget -nc -q https://raw.githubusercontent.com/asciidoctor/asciidoctor-pdf/master/data/themes/default-theme.yml -O /default-theme.yml
      - find . -name '*.adoc' -not -path "*./heat*" | while read adoc;do asciidoctor-pdf --trace -a allow-uri-read -a pdf-style=/default-theme.yml $adoc;done
  artifacts:
    untracked: true

genpdf:
  script:
      - wget -nc -q https://git.cybbh.space/global-objects/binaries/raw/master/wkhtmltopdf -O ./wkhtmltopdf && chmod +x ./wkhtmltopdf
      - wget -nc -q https://git.cybbh.space/global-objects/resources/raw/master/css/cted0001.css -O ./cctc.css
      - find . -name '*.adoc' -not -path "*./heat*" | while read adoc;do asciidoctor --verbose $adoc;done
      - find . -name '*.html' -not -path "*./networking/slides*" -not -path "*./windows/slides*" | while read html;do file=$(echo $html | sed 's/\.[^.]*$//') && ./wkhtmltopdf $html $file.pdf; done

  artifacts:
    paths:
      - ./*.pdf
      - ./*/*.pdf
      - ./*/*/*.pdf
      - ./*/*/*/*.pdf

networking_slides_adoc:
  script:
    - cd networking/slides/adoc
    - bundle config --local github.https true
    - bundle --path=.bundle/gems --binstubs=.bundle/.bin
    - find . -name '*.adoc'| while read adoc;do bundle exec asciidoctor-revealjs -a revealjsdir=https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.6.0 $adoc;done
  artifacts:
    paths:
    - networking/slides/adoc/*.html
    - networking/slides/adoc/*/*.html