:doctype: book
:stylesheet: ../../cctc.css

= Activity - Netcat Relays

== Learning Objectives

* CCNE008.005 - Explain the forward and reverse file transfer process with netcat
* CCNE008.006 - Demonstrate the process for transferring files via terminal

== Learning Outcomes

* N/A

== Scenario

* You will be transferring files between net1 and the DMZ client using the net3 client as a relay.

=== Task 1) 

* Send secrectstuff.txt from net1 to the DMZ Client. net3 will be the relay. You *CANNOT* make *outbound* connections on net3.
** Create a file named "secretstuff.txt" on the net1 host. Write the message "This is important information" into the file. You will be sending this to the DMZ host through a relay at net3.
** For the transfer of "secretstuff", net3 cannot make outbound connections.

=== Task 2) 

* Send supersecrectstuff.txt from net1 to the DMZ Client. net3 will be the relay. You can *ONLY* make *outbound* connections on net3.
** Create a file on the net1 client named "supersecretstuff.txt" and write the message "passwords should be complex" into the file. You will be sending this to the DMZ client through a relay on net3.
** For the transfer of "supersecretstuff", net3 can only make outbound connections.

=== Task 3) 

* Send secrectsquirrelstuff.txt from net1 to the DMZ Client. net3 will be the relay. You can *ONLY* make *outbound* connections on net1, and you can *ONLY* make *inbound* connections on the DMZ client.
** Create a file on the net1 client named "secretsquirrelstuff.txt" and write the message "awww nuts" into the file. You will be sending this to the DMZ client through a relay on net3.
** For the transfer of "secretsquirrelstuff", the relay for net3 should be configured to ensure the net1 is making an *outbound* connection, while the DMZ Client is making an *inbound* connection.

== Deliverables

* Screenshots showing your commands and the successful file transfers
* An explanation of the commands/process you used to transfer the files through the relay

== Hints

* N/A

== Challenge

* N/A

== Useful Resources

* N/A
