:doctype: book
:stylesheet: ../../cctc.css

= Activity – New Registry Key

== Learning Objectives

* CCWI000 - 
** CCWI000.000 - 

== Learning Outcomes

* Familiarity with the Windows registry and methods to interact with it
* Familiarity with forensically relevant Windows registry keys and run keys
* Confidence editing registry keys for specific purposes
* Capability to use the Windows registry to store informatio 

== Scenario

* You are implementing a new security logging policy. You want to run a logging script that tracks the number of system reboots and logs reboots automatically to a file. Additionally, you want to run a script generates a log every time users log into the system.

=== Task 1)

* Create a PowerShell script that adds the appropriate registry keys to run the appropriate scripts when the system is launched and when users log on.

=== Task 2)

* Create a PowerShell script that is run when the system is launched. This script will store the number of reboots in a registry entry and increment that number. The script should also log the system date and time and number of reboots to a file. The log file should be appended with every reboot, not overwritten.

=== Task 3)

* Create a PowerShell script that is run when a user logs on. This script should log the system date and time that a user logged in to the same log file.

== Deliverables

* The script that adds the appropriate registry keys
* The script that is run when the system is launched
* The script that is run when a user logs on
* The output of your log file with at least two computer restarts and one user login.

== Hints

* N/A

== Challenge

* N/A

== Useful Resources

* N/A