:doctype: book
:stylesheet: ../../cctc.css

= Activity – New Registry Key
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Scenario

You are implementing a new security logging policy. You want to run a logging script that tracks the number of system reboots and logs reboots automatically to a file. Additionally, you want to run a script generates a log every time users log into the system.

== Activity

Create a PowerShell script that adds the appropriate registry keys to run the appropriate scripts when the system is launched and when users log on.

Create a PowerShell script that is run when the system is launched. This script will store the number of reboots in a registry entry and increment that number. The script should also log the system date and time and number of reboots to a file. The log file should be appended with every reboot, not overwritten.

Create a PowerShell script that is run when a user logs on. This script should log the system date and time that a user logged in to the same log file.

== Deliverables

[square]
* The script that adds the appropriate registry keys
* The script that is run when the system is launched
* The script that is run when a user logs on
* The output of your log file with at least two computer restarts and one user login.

== Learning Objectives / Outcomes

[square]
* Familiarity with the Windows registry and methods to interact with it
* Familiarity with forensically relevant Windows registry keys and run keys
* Confidence editing registry keys for specific purposes
* Capability to use the Windows registry to store information
