:doctype: book
:stylesheet: ../../cctc.css

= Activity - Brute Force
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Scenario

You are operating from a US allied server with access to behind-enemy-lines computers, via SSH, and aquired creds.  One of the computers is believed to contain stolen GoldCodes for the President's Nuclear Arsenal.  Intel suggests proof of the codes existence will be difficult to obtain, as the codes are systematically moved from system to system at random intervals.  Further it is believed that around 10 of the 34 launch codes were compromised.  The President has classified this information, as such, you should expect no help from the outside world, however, you are permitted a search engine for research purposes.  It is up to you to quickly determine which launch codes were compromised, to facilitate a code turn-over.  If all of the compromised codes are not changed in 1 hour, the launch-control program will activate the fail-safe protocol, and launch all the missiles. The fate of the free world is in your hands.  No Pressure.

Research: https://whitehouse.gov1.info/launch/

== Activity

Design a bash script to connect to the Linux target(s), and extract the GoldCodes, via 'scp' using the information provided here:

Tip:  US_SECRET_SERVICE_MSG001:

Agent, the Gold Codes are alpha-numeric only, and usually between 35 and 40 characters long.  The document they were contained in, if still intact, should contain the similiar phrase: "Take em out with the Ball Game" . Good Luck, Agent!

Tip:  Concerned Secret Org Communique:

Greetings, Comrade.  I have information that may prove useful in your current situation. We intercepted it from a base in the far region, known only as "16". Perhaps you will have better fortune then we have decoding it. p.s. Password are 'EasilyBypassed'

"[Encoded MSG002]:   687474703A2F2F74696E7975726C2E636F6D2F676E656668747000   [End Encoded MSG002]"

NickCiske.comrade


== Check Your work

$ echo <md5sum sorted-last Gold-Code> | md5sum

eb470094652a7fc564687ff30df472b4

== Learning Objectives / Outcomes

[square]
* Familiarity with Regular Expressions, and how to script for them
* Ability to analyze mission data and devise a scripted strategy for success
* Ability to deduce from data, key words used for targeted web research