:doctype: book
:stylesheet: ../../cctc.css

= Activity - Funny Traffic
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Learning Objectives / Outcomes
[square]
* SKILL CCNE009: Identify packet sniffing tools
** CCNE009.003 Demonstrate packet decoding features of tools

{empty} +

== Activity

{empty} +

Your team has been conducting traffic analysis for a network which was compromised. The team has asked you to look at (3) samples that stood out as anomalies.

You can find the PCAP resources in the networking folder of the resource server at:

https://git.cybbh.space/CCTC/public/raw/master/networking/additional_resources/AreyouGettingthis.pcap

https://git.cybbh.space/CCTC/public/raw/master/networking/additional_resources/SANTA.pcap

{empty} +

=== Task 1)
Based on the raw data for sample 1, or PCAPs provided for Samples 2-3, answer the following questions about the nature/details of the traffic you are analyzing.

1) What is anomalous about this traffic? 

2) How could traffic like this be used in an exploit situation?

3) Is this something you can defend against?  If so, how?

Sample 1- See the "SANTA.pcapng" file

Sample 2 (these two packets are related, consider how they are related)

Packet 1:

00 00 39 CF D9 CD 00 40 33 D9 7C FD 08 00 45 00 00 38 00 F2 20 00 40 11 AF 37 0A 01 01 01 81 6F

1E 1B 7C AB 4E E5 00 24 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

00 00 00 00 00 00

Packet 2:

00 00 39 CF D9 CD 00 40 33 D9 7C FD 08 00 45 00 00 18 00 F2 00 03 40 11 CF 54 0A 01 01 01 81 6F

1E 1B 7C AB 4E E5

Sample 3- See the "Are your getting this.pcap" file
  (hint- follow the tcp stream starting at the HTTP Get request, packet 4)
  
{empty} +

== Deliverables
[square]
* Complete answers to the above questions for traffic samples 1-3.

{empty} + 


