:doctype: book
:stylesheet: ../../cctc.css

= Activity - Analyze Patches
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Learning Objectives / Outcomes
* CCWI001.001: Use command line commands to gain situational awareness of the current workstation
* CCWI002.001: Use WMIC commands to gain situational awareness of the current workstation
* CCWI003.001: Identify the purpose of using Powershell in operations
* CCWI004: Develop scripts
* CCWI012: Identify the importance of situational awareness

{empty} +

== Scenario
You have successfully exploited onto an endpoint device and you have a privilege escalation tool(ROBOTDORITOS) in your arsenal that you intend on using to gain system privilege in order to lay down a rootkit.
However, new technical guidance came out that you are required to adhere to.

Techincal Guidance:
EFFECTIVE IMMEDIATELY!!!!
Summary:
A recent software patch for Common Vulnerabilities and Exposures 2016-3251 was released.
This update renders the following tools ineffective:
-ROBOTDORITOS

Guidance:
Verify the installation status for the patch. If the patch is not installed, you may deploy ROBOTDORITOS.
If the patch is installed and the operation cannot continue without the use of ROBOTDORITOS, cease operations.

{empty} +

== Activity

=== Task 1)
Write a PowerShell script that will determine if the endpoint you are on is vulnerable to ROBOTDORITOS.

=== Task 2)
Provide a technical summary that outlines your recommended course of action.

== Deliverables

[square]
* A PowerShell script that verifies whether or not the endpoint is vulnerable to ROBOTDORITOS
* The output of the PowerShell script
* A technical summary that outlines your recommended course of action.

{empty} +

== Hints
N/A

{empty} +

== Challenge
N/A

{empty} +

== Useful Resources
"CVE-2016-3251," Microsoft Corporation. https://www.cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-3251
