== Nipper Demo

{empty} +

*Learning Objectives / Outcomes*

** 2.5 Discuss best practices for network analysis
** 3.1 Analyze a router configuration and create a network map

{empty} +

== Demo Walk-through

{empty} +

_NIPPER is a vulnerability auditing tool that can be found in Kali linux, or downloaded from their git repo. The tool is available for free (with limited device support) 
on linux of windows. There is also a paid version of this tool which supports nearly all major vendor network devices and OSes. This is a useful tool to use when getting familiar 
with vulnerability auditing for network devices. It provides the vulnerability found, the impact of it and the fix action commands._

{empty} +

In this demonstration, H1 (Debian GUI host) will need to download the router configuration file that the students use in their "Mapping a Network" activity.

*Follow the below steps*


{empty} +


=== NIPPER Vulnerability Auditing Tool
 
{empty} +
 
1) Log into H1. It is best to make yourself root, so you don't have to use sudo as you bring up the tool.

2) Clone the git repo for the nipper tool with the command: "git clone git://git.kali.org/packages/nipper-ng.git"

3) CAT the INSTALL file and follow the installation commands.

4) Once installed, you can run a configuration document through the tool to output a report.

5) Use the command: "nipper --ios-router --input=/dir/file.txt --output=/dir/report.html"


_The input and output directory and file name are based on where you placed the configuration file in your host and where you want to create the report._


6) Locate the report in the directory that you created and open it. It should render in a browser with all the vulnerability information, impact, and fix actions

{empty} +

 
*References:* 

** http://tools.kali.org/reporting-tools/nipper-ng
