:doctype: book
:stylesheet: ../../cctc.css

= Activity - SysInternals Process Tools
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Learning Objectives / Outcomes

[square]
* CCWI001.002: Use System Internals tools to gain situational awareness of the current workstation
* CCWI008.001: Explain how to find the current status of a Windows process
* CCWI008.002: Explain the process states and identify why they are important
* CCWI031.001: Identify baseline knowledge on a machine
* CCWI031.002: Gather baseline knowledge on a machine

{empty} +

== Scenario
N/A

{empty} +

== Activity

=== Task 1)
Download the SysInternals Suite to your Windows system from TechNet at: +
https://technet.microsoft.com/en-us/sysinternals/bb842062.aspx

Run the following SysInternals tools to get familiar with their functionality:

[square]
* Process Explorer
* Process Monitor
* PsList
* PsKill
* PsSuspend
* PsService
* ListDLLs

=== Task 2)
Complete the following tasks and document the tool and process used to compete the task:

[square]
* Launch Notepad, create a new txt document and save it to the desktop. With Notepad still open, identify the file that is open (presuming you do not already know). 
* Force kill the active running instance of Notepad.
* Identify all the registry entries that are accessed, edited, and created when launching Notepad and accessing a single .txt file.
* Launch Notepad on your Windows 7 system. Query the processes running on your Windows 7 system from your Windows 10 system. Kill Notepad on your Windows 7 system from your Windows 10 system.
* Launch Notepad on your Windows 7 system. Suspend the Notepad process from your Windows 10 machine.
* Query the services running on your Windows 7 system from your Windows 10 system. Stop the Windows Defender service on Windows 7 from Windows 10. Verify that the service was stopped in Windows 7. Restart the service from Windows 10.

{empty} +

== Deliverables

[square]
* A document summarizing your process used to accomplish the tasks

{empty} +

== Hints
N/A
