:doctype: book
:stylesheet: ../../cctc.css

= Activity - Follow a Packet Through a Network

== Learning Objectives

* SKILL CCNE001: Understand Switching Technologies
* SKILL CCNE002: Understand Routing Technologies
* SKILL CCNE003: Understanging Static vs Dynamic Routing
* SKILL CCNE004: Understanding Distance Vector vs Link State Routing Protocols

== Learning Outcomes

* N/A

== Scenario

* The network provided is a fully functioning network with many different protocols working to function.

* Router login usernames will be "cctc"

* All device passwords for this Activity is "password"


=== Task 1)


. Download the CCTC.pkt file.

** Download: https://git.cybbh.space/CCTC/public/tree/master/networking/Activity-Follow_a_packet_through_a_network/CCTC.pkt on to your Net1. 

** Optionally you can download to your host box and use SCP to copy to Net1. "scp /home/username/Downloads/CCTC.pkt username@{net1 floating ip} /home/username".

. Startup Packet Tracer on Net1. 

** Open Net 1 on the VTA, open a Terminal Window and type "packettracer".

** Optionally you can run Packet Tracer on your host box from Net1: "ssh username@{net1 floatingip} -X" then run "packettracer".

** Another option is to connect to your Net1 with xfreerdp. "xfreerdp /v:{net1 floating ip}  /u:username /p:password /size:1920x1000  + clipboard"

. Upon startup you will be asked for login credentials (which you will not have). Click the "Guest Login" at the bottom. After 10-15 seconds you can click "Confim Guest" to open the program. A webpage will open but you can close this window.

. From Packet Tracer, open the CCTC.pkt file that you downloaded. 

. Upon opening, the virtual systems will boot up and start communicating. Give it a few moments for the Bootup, Spanning-tree and DHCP to complete.

. During this Activity:

*** You can switch between "Realtime" and "Simulation" by clicking the icons in the bottom right corner on the window. You will be navigating between these modes for this Activity. 

*** You will be required to select appropriate protocols under the "Event List Filters - Visible Events" window in the "Simulation" tab or each of the steps. To select the appropriate protocol select "Edit Filters". Would not recommend to have additional protocols selected as this will populate alot of extra information.

*** To start a packet capture, ensure you are in "Simulation" and have edited the filter for the proper protocol(s). After you perform an action, you can capture 1 packet at a time by using the "Capture/Forward" or "Back" to move forward and backwards. To start capturing all packets you can select "Auto Capture/Play" in the "Play Controls" window.

*** In the "Event List" window you will see your packet captures. Click them to view the packet contents. On some events you will see "Inbound" and "Outbound" tabs to identify the direction of traffic.

*** You can click to open any of the items on the network. The tab you will generally be using is the "Desktop" tab. On the Routers and Switches you will use the "CLI" tab.

=== Task 2)

* Ensure that you are in "Simulation" mode for this Acitivty.

. DHCP

** Click to open any one of the Instructor laptops. Goto Desktop --> Command Prompt. Renew the IP address by typing in "ipconfig /renew". Follow the traffic from the host to the DHCP server.

*** 1. What type of traffic was initated by the Instructor laptop?

*** 2. What is the destination MAC address of the inital packet sent by the host?

*** 3. What is the destination IP address of the inital packet sent by the host?

*** 4. What is the source and destination ports?

*** 5. Where the Ether Type value would normally be, what did the value change to when it leaves the first switch?

*** 6. Which VLAN was it assigned to?

*** 7. What did the switch do with this traffic?

*** 8. What what did the VLAN change to when it left the router?

*** 9. What did the destination IP address change to?

*** 10. What caused this to happen?

*** 11. What did the switch change the Type field to as it left the switch?

*** 12. What response did the server give?

*** 13. What response did the instructor laptop give to respond to the traffic from the DHCP server?

*** 14. What was the final response from the DHCP server?

*** 15. What network are the Instructor laptops assigned to?

** Repeat previous step on each of the Student, Instructor, and Guest laptops. 

*** 16. hat VLAN are the Students assigned to?

*** 17. What Network are the Students assigned to?

*** 18. What VLAN are the Guest assigned to?

*** 19. What Network are the Guests assigned to?

. ICMP and ARP

** From any Instructor laptop, ping the IP address of any of the other Instructor laptops.

*** 1. What protocol initiated before the ICMP packet started?

*** 2. What was the Type value?

*** 3. What was the target MAC address?

*** 4. What was the response from the destination device?

*** 5. What was the Type and Code values of the Ping that was sent?

*** 6. What was the Type and Code Values of the response from the destination?

** From a different Instructor laptop, ping the IP address of any of the Student laptops.

*** 7. Who responded to the ARP request?

** From any of the Guest laptops, ping any Instructor or Student system. 

*** 8. What type of frame did it use over the Wireless network?


. NAT

** From an Instructor Laptop, ping the 147.51.0.1 DMZ Gateway. Follow the Traffic. On the private/public boundry, what address did the router change the source address to?

** From a Student Laptop, ping the same IP. Follow the traffic. What address did it change the source IP to?

** From a Guest Laptop, ping the same IP. Follow the traffic. What address did it change the source IP to?


. TCP, HTTP, HTTPS, and DNS

** From any of the Instructor, Student or Guest laptops. Goto Desktop --> Web Browser. In the URL enter "http://www.cctc.mil". 

*** 1. What type of traffic did the host initate first?

*** 2. What was the destination port?

*** 3. What server did that traffic goto?

*** 4. What was the destination IP?

*** 5. What is the IP protocol number?

*** 6. What was the response from the destination device?

*** 7. What type of traffic did the host iniated second? 

*** 8. What was the destination port?

*** 9. What server did that traffic goto?

*** 10. What was the destination IP?

*** 11. What is the IP protocol number?

*** 12. What was the FLAG(s) set to as it left the host?

*** 13. What was the FLAG(s) set to as the response left the destination?

*** 14. What was the FLAG(s) set to when the host gave its final reponse?

*** 15. What type of traffic did the host initate third?

*** 16. What is the FLAG(s) set to?

*** 17. What is the FLAG(s) set to once communication was completed?

** Browse to "https://www.cctc.mil". 

*** 18. What was the destination port that is used in this case?


. SMTP and POP3

** Open any 2 laptops and place the windows side by side. Goto Desktop --> Email on each. On one laptop, click "Compose". In the "To:" block, enter the other laptop username and number then "@cctc.mil". (i.e. instructor1@cctc.mil or student4@cctc.mil). Enter any Subject and body then click "Send". Follow the traffic. 

*** 1. What server did the laptop initiate a connection with?

*** 2. What destination port number did it attempt to connect to?

*** 3. What protocol did it use to sent the email?

** Click "Reset Simulation". Then on the receiving laptop click "Receive".

*** 4. After the 3-way handshake, what portocol did it use to retrieve the email?

*** 5. What destination port number did it use?


. Telnet, SSH, TACACS+

** From any laptop, Goto Desktop --> Command Prompt. Telent to that computers local gateway IP address.

*** 1. What port destination port did the laptop use to connect?

*** 2. After the 3-way handshake, what FLAG(s) send back to host?

*** 3. Why did you get this flag?

** Try to SSH to the same IP (ssh -l cctc {ip address}). Follow the TCP traffic. After the 3-way handshake it will eventually ask for the password to continue. 

*** 4. What FLAG(s) were set to send the password?

*** 5. What port and protocol was used to send the password?

*** 6. What device did the Gateway communicate with afterwards?

*** 7. What protocol and port did it use to communicate?



. WAN access and HTTP/HTTPS

** From any laptop. Browse to www.comcast.com external website. Follow the traffic.

*** 1. What Layer 2 protocol is used over the Internet past the ISPs?

*** 2. What address (decimal) did the ISP use to communicate to the internet?

*** 3. What address (decimal) did the Internet use to communicate to Comcast?


=== Task 2)

. Monitor all traffic. 

** 1. What types of routed protocols do you see running?

** 2. What types of routing protocols are running? 


=== Task 3)

. Malicious attackers will try to access your network. Connect a straight-thru cable from "Rogue" switch. Click on the lightning bolt icon in the bottom left, then select solid black line icon. 

** Click on the "Rogue" switch and select any of the open ports available. Then click on "CCTC_SW_4" and connect it to port "FastEthernet0/20". 

*** 1. What happened to the connection? 

*** 2. Can the Rogue PC attain an IP address? 

*** 3. What protocol/feature made this happen?

*** 4. Connect the "Rogue" switch to any other interface. What happened to the connection?

*** 5. Can the Rogue PC attain an IP address? 

*** 6. What protocol/feature made this happen?


== Deliverables

* Follow through the Activity and document each answer to the questions in a text editor. 
* Be prepared to discuss your discoveries with the class. 

== Hints

* N/A

== Challenge

* N/A

== Useful Resources

* N/A
