:doctype: book
:stylesheet: ../../cctc.css

= Activity - Follow a Packet Through a Network

== Learning Objectives

* SKILL CCNE001: Understand Switching Technologies
* SKILL CCNE002: Understand Routing Technologies
* SKILL CCNE003: Understanging Static vs Dynamic Routing
* SKILL CCNE004: Understanding Distance Vector vs Link State Routing Protocols

== Learning Outcomes

* N/A

== Scenario

* The network provided is a fully functioning network with many different protocols working to function.

* Router login usernames will be "cctc"

* All device passwords for this Activity is "password"


=== Task 1)


. Download the CCTC.pkt file.

** Download: https://git.cybbh.space/CCTC/public/tree/master/networking/Activity-Follow_a_packet_through_a_network/CCTC.pkt on to your Net1. 

** Optionally you can download to your host box and use SCP to copy to Net1. "scp /home/username/Downloads/CCTC.pkt username@{net1 floating ip} /home/username".

. Startup Packet Tracer on Net1. 

** Open Net 1 on the VTA, open a Terminal Window and type "packettracer".

** Optionally you can run Packet Tracer on your host box from Net1: "ssh username@{net1 floatingip} -X" then run "packettracer".

** Another option is to connect to your Net1 with xfreerdp. "xfreerdp /v:{net1 floating ip}  /u:username /p:password /size:1920x1000  + clipboard"

. Upon startup you will be asked for login credentials (which you will not have). Click the "Guest Login" at the bottom. After 10-15 seconds you can click "Confim Guest" to open the program. A webpage will open but you can close this window.

. From Packet Tracer, open the CCTC.pkt file that you downloaded. 

. Upon opening, the virtual systems will boot up and start communicating. Give it a few moments for the Bootup, Spanning-tree and DHCP to complete.

. During this Activity:

*** You can switch between "Realtime" and "Simulation" by clicking the icons in the bottom right corner on the window. You will be navigating between these modes for this Activity. 

*** You will be required to select appropriate protocols under the "Event List Filters - Visible Events" window in the "Simulation" tab or each of the steps. To select the appropriate protocol select "Edit Filters". Would not recommend to have additional protocols selected as this will populate alot of extra information.

*** To start a packet capture, ensure you are in "Simulation" and have edited the filter for the proper protocol(s). After you perform an action, you can capture 1 packet at a time by using the "Capture/Forward" or "Back" to move forward and backwards. To start capturing all packets you can select "Auto Capture/Play" in the "Play Controls" window.

*** In the "Event List" window you will see your packet captures. Click them to view the packet contents. On some events you will see "Inbound" and "Outbound" tabs to identify the direction of traffic.

*** You can click to open any of the items on the network. The tab you will generally be using is the "Desktop" tab. On the Routers and Switches you will use the "CLI" tab.

=== Task 2)

* Ensure that you are in "Simulation" mode for this Acitivty.

. DHCP

** Click to open any one of the Instructor laptops. Goto Desktop --> Command Prompt. Renew the IP address by typing in "ipconfig /renew". Follow the traffic from the host to the DHCP server.

*** What type of traffic was initated by the Instructor laptop?

*** What is the destination MAC address of the inital packet sent by the host?

*** What is the destination IP address of the inital packet sent by the host?

*** What is the source and destination ports?

*** Where the Ether Type value would normally be, what did the value change to when it leaves the first switch?

*** Which VLAN was it assigned to?

*** What did the switch do with this traffic?

*** What what did the VLAN change to when it left the router?

*** What did the destination IP address change to?

*** What caused this to happen?

*** What did the switch change the Type filed to as it left the switch?

*** What response did the server give?

*** What response did the instructor laptop give to respond to the traffic from the DHCP server?

*** What was the final response from the DHCP server?

*** What network are the Instructor laptops assigned to?

** Repeat previous step on each of the Student, Instructor, and Guest laptops. 

*** What VLAN are the Students assigned to?

*** What Network are the Students assigned to?

*** What VLAN are the Guest assigned to?

*** What Network are the Guests assigned to?

. ICMP and ARP

** From any Instructor laptop, ping the IP address of any of the other Instructor laptops.

*** What protocol initiated before the ICMP packet started?

*** What was the Type value?

*** What was the target MAC address?

*** What was the response from the destination device?

*** What informaiton was provided from the destination device?

*** What was the Type and Code values of the Ping that was sent?

*** What was the Type and Code Values of the response from the destination?

** From a different Instructor laptop, ping the IP address of any of the Student laptops. What diferences did you notice about the flow of traffic?

*** Who responded to the ARP request?

** From any of the Guest laptops, ping any Instructor or Student system. 

*** What type of frame did it use over the Wireless network?

. TCP, HTTP, HTTPS, and DNS

** From any of the Instructor, Student or Guest laptops. Goto Desktop --> Web Browser. In the URL enter "http://www.cctc.mil". 

*** What type of traffic did the host initate first?

*** What was the destination port?

*** What server did that traffic goto?

*** What was the destination IP?

*** What is the IP protocol number?

*** What was the response from the destination device?

*** What type of traffic did the host iniated second? 

*** What was the destination port?

*** What server did that traffic goto?

*** What was the destination IP?

*** What is the IP protocol number?

*** What was the FLAGS set to as it left the host?

*** What was the FLAGS set to as the response left the destination?

*** What was the FLAGS set to when the host gave its final reponse?

*** What type of traffic did the host initate third?

*** What is the FLAGS set to?

** Browse to "https://www.cctc.mil". 

*** What was the destination port that is used in this case?


. SMTP and POP3

** Open any 2 laptops and place the windows side by side. Goto Desktop --> Email on each. On one laptop, click "Compose". In the "To:" block, enter the other laptop username and number then "@cctc.mil". (i.e. instructor1@cctc.mil or student4@cctc.mil). Enter any Subject and body then click "Send". Follow the traffic. On the other laptop click "Receive" and then follow the traffic. 

. Telnet, SSH, TACACS+

** From any laptop, Goto Desktop --> Command Prompt. 

*** Telent to that computers local gateway IP address. What happened? Why?

*** Try to SSH to the same IP (ssh -l cctc {ip address}). Follow the traffic. Eventually it will ask for the password to continue. Then continue to follow traffic. What happened?

. WAN access with ICMP and HTTP/HTTPS

** From any laptop. Ping the ip address of any of the webservers across the "internet". Follow the traffic. What happened specifically at the CCTC_RTR in regards to the IP address? What happened to the traffic as it flowed from Cyber_CTC to the WAN? What was different about the traffic as it flowed through the internet and then to the remote site?

** Browse to each of the seperate external websites.


=== Task 2)

. Monitor all traffic. 

** What types of routed protocols do you see running?

** What types of routing protocols are running? What information can you gather from the data traffic?


=== Task 3)

. Malicious attackers will try to access your network. Connect a straight-thru cable from "Rogue" switch. Click on the lightning bolt icon in the bottom left, then select solid black line icon. 

** Click on the "Rogue" switch and select any of the open ports available. Then click on "CCTC_SW_4" and connect it to port "FastEthernet0/20". 

*** What eventually happened? 

*** Can the Rogue PC attain an IP address? 

*** How was this able to happen?

*** What happens if you connected the "Rogue" switch to any other interface?



== Deliverables

* Follow through the Activity and document each answer to the questions in a text editor. 
* Be prepared to discuss your discoveries with the class. 

== Hints

* N/A

== Challenge

* N/A

== Useful Resources

* N/A
