:doctype: book
:stylesheet: ../../cctc.css

= Activity - MBRoken
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Learning Objectives

* CCNI004 - Describe the Linux boot process
* CCNI004.001 - Identify components of the boot process
* CCNI004.004 - Describe partitions

{empty} +

== Outcomes

[square]
* Familiarity with the parts of a correctly formatted Linux MBR
* Ability to analyze an MBR using CLI binaries and identify misconfigurations.
* Operational Context: http://www.pcworld.com/article/3046626/security/petya-ransomware-overwrites-mbrs-locking-users-out-of-their-computers.html

{empty} +

== Scenario

The hard drive in your Commander's laptop, containing critical files, stopped responding after a network-wide malware attack. You're fairly certain the problem has something to do with the HD's MBR (file: "mbroken").

{empty} +

== Activity

You have access to a broken generic MBR. Fix the MBR so your career doesn't go down the drain along with those files. The file is located here: */usr/share/cctc/mbroken.zip*

Start by verifying that you have the correct boot record file. Unzip the file and check its MD5 hash: b73f30cf162511fe8429ff907a5a9f53

Both Ubuntu and Debian are permitted for this exercise.

=== Task 1)

Find the MD5 hash of the bootstrap code.

=== Task 2)

Find the MD5 hash of the second partition entry.

=== Task 3)

Figure out what's still wrong with the MBR. Find the hex characters (ALL CAPS, no spaces).
NOTE: You are looking for a string of hex characters (i.e. "DEADBEEF").

{empty} +

== Deliverables

Check your work using MD5 hashes. Use the `md5sum` command: `$ CMD... | md5sum`

* Bootstrap code: d59a68c7b6d62ecaa1376dfb73a3b7be
* Second partition: 41a8cbc4d7314c23c7e7f6b0a799d76b
* Hex string: d7c07574567e1af6856be94a590ec2dc

{empty} +

== Hints

* `dd`, `hexdump`
* Read up on the specs for a properly forumated MBR
* Your endian may be off

{empty} +

== Challenge

NONE

{empty} +

== Useful Resources

* http://thestarman.pcministry.com/asm/mbr/PartTables.htm
