:doctype: book
:stylesheet: ../../cctc.css

= Activity - Baseline Your Registry
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Learning Objectives / Outcomes
* CCWI003.001: Identify the purpose of using Powershell in operations. +
* CCWI014.002: Use command line syntax to query, view, analyze, modify and create Registry values. +
* CCWI015.001: Identify Registry locations that contain forensically relevant information. +
* CCWI015.002: Identify Registry locations that can be utilized for persistence. +
* CCWI015.003: Perform basic analysis on a Windows system with a compromised Registry. +

{empty} +

== Scenario

You want to enumerate your registry to create a baseline for future forensic reference and to take registry snapshots at specific points in time. Additionally, you want easily to identify registry changes over time by comparing results from different runs of this baseline script.

{empty} +

== Activity

Create a PowerShell script that queries the registry and records the values and data from forensically relevant registry keys. Write a second script that compares the output of two baseline runs and identifies differences between run times. This script should input the two datasets as command line arguments. For best results, this script alerts only the specific information that is different.

=== Task 1)

Query registry and record values and data from relevant keys

=== Task 2)

Script that compares two registry baselines +
script should take the two files as command line arguments

{empty} +

== Deliverables

* The script that baselines the registry
* The output of your baseline registry script
* The script that compares baseline runs
* The output of the script that compares two runs

{empty} +

== Hints

if your script is taking too long to run try looking at some CMD commands to baseline the registry.

{empty} +

== Challenge

Script alerts on only specific information that is different.

{empty} +

== Useful Resources
* "Windows registry information for advanced users," Microsoft Corporation. https://support.microsoft.com/en-us/help/256986/windows-registry-information-for-advanced-users

* "Using the Get-ItemProperty Cmdlet," Microsoft Corporation. https://technet.microsoft.com/en-us/library/ee176852.aspx

* "Predefined Keys," Microsoft Corporation. https://msdn.microsoft.com/en-us/library/windows/desktop/ms724836(v=vs.85).aspx

* "What are Control Sets? What is CurrentControlSet?" Microsoft Corporation. https://support.microsoft.com/en-us/help/100010/what-are-control-sets-what-is-currentcontrolset

* "Hivelist," Microsoft Corporation. https://technet.microsoft.com/en-us/library/cc951686.aspx
