:doctype: book
:stylesheet: ../../cctc.css

= Activity - COA Development for DCO-RA
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Activity: COA Development for DCO-RA
A critical server is being Dos’d by an adversary. You must conduct a Defensive Cyber Operations (DCO) Response action (DCO-RA) to stop the attack. 
As a group, you must first develop 3 technical courses of action using the Military Decision Making Process (MDMP).
You have leveraged your intelligence sources and discovered that the attacking machine is a windows 7 box located in Denovia.
The machine was compromised in the past but has since been patched and the credentials have changed, therefore the exploits and credentials you have at your disposal will not grant you access.
Utilizing the skills, and concepts you have learned in this module, stop the attack.
Ultimately the instructor will approve one of your COAs and allow you to attempt to stop the denial of service attack.


[square]
* Understand scenario
* Develop COAs
* Discuss the implications of the technical courses action you develop
* Propose your COAs
* Carry out a valid DCO-RA based off your COA


== Deliverables
[square]
* Stop the denial of service attack



== Learning Objectives / Outcomes
[square]
* Become familiar with incident response
* Obtain a hands on practical application for Course of Action Development
* Demonstrate the fundamentals of everything learned in the Windows module