heat_template_version: 2016-10-14

description: Heat Template for Linux Final - Attaches Linux Final to Student Linux Stack

parameters:

  student_id:
    type: string
    label: Student ID
    description: Student ID Number with No Leading Zeros

  last_name:
    type: string
    label: Last Name
    description: Last Name
    default:
    constraints:
      -  length: { min: 1, max: 15 }
         description: Last name must be no longer than 15 characters
      -  allowed_pattern: "[a-zA-Z]*"
         description: Last name may only contain letters

resources:

  host5-port:
    type: OS::Neutron::Port
    properties:
      network_id:
        str_replace:
          template: lastName_Network
          params:
            lastName: { get_param: last_name }
      fixed_ips:
        - subnet_id:
            str_replace:
              template: lastname_subnet
              params:
                lastname: { get_param: last_name }
          ip_address:
            str_replace:
              template: 10.studentID.0.5
              params:
                studentID: { get_param: student_id }
      port_security_enabled: false

  host5:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: lastname-Linux-final
          params:
            lastname: { get_param: last_name }
      image: Linux Final Retake
      flavor: cy.small
      networks:
        - port: { get_resource: host5-port }
