heat_template_version: 2017-02-24

description: Heat Template for Linux module of class - Debian Jessie , Ubuntu 16.04 & Windows 7

parameters:

  student_id:
    type: string
    label: Student ID
    description: Student ID Number with No Leading Zeros

  last_name:
    type: string
    label: Last Name
    description: Last Name
    default:
    constraints:
      -  length: { min: 1, max: 15 }
         description: Last name must be no longer than 15 characters
      -  allowed_pattern: "[a-zA-Z]*"
         description: Last name may only contain letters

  password:
    type: string
    label: Password
    description: Set root/admin password for instances
    hidden: true
    default:
    constraints:
      -  length: { min: 8, max: 20 }
         description: Password must be between 8 and 20 characters
      -  allowed_pattern: "[a-zA-Z0-9]*"
         description: Password may not contain special characters

resources:

  stu-network:
    type: OS::Neutron::Net
    properties:
      name:
        str_replace:
          template: lastName_Network
          params:
            lastName: { get_param: last_name }
      admin_state_up: true
      shared: false

  stu-subnet:
    type: OS::Neutron::Subnet
    properties:
      allocation_pools:
        - start:
            str_replace:
              template: 10.studentID.0.200
              params:
                studentID: { get_param: student_id }
          end:
            str_replace:
              template: 10.studentID.0.250
              params:
                studentID: { get_param: student_id }
      cidr:
        str_replace:
          template: 10.studentID.0.0/24
          params:
            studentID: { get_param: student_id }
      gateway_ip:
        str_replace:
          template: 10.studentID.0.254
          params:
            studentID: { get_param: student_id }
      network_id: { get_resource: stu-network }
      dns_nameservers: [10.50.255.254]
      enable_dhcp: true
      host_routes: []
      ip_version: 4
      name:
        str_replace:
          template: lastname_subnet
          params:
            lastname: { get_param: last_name }

  stu-router:
    type: OS::Neutron::Router    
    properties:
      name:
        str_replace:
          template: lastname_router
          params:
            lastname: { get_param: last_name }
      external_gateway_info: {"network": public}

  stu-router-interface:
    type:  OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: stu-router }       
      subnet_id: { get_resource: stu-subnet }
      
  float_ip_1:
    type: OS::Neutron::FloatingIP
    depends_on: stu-router
    properties: { floating_network: public }

  float_port_1:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: stu-network }
      fixed_ips:
        - subnet_id: { get_resource: stu-subnet }
          ip_address:
            str_replace:
              template: 10.studentID.0.1
              params:
                studentID: { get_param: student_id }
      port_security_enabled: false
      
  float_ip_assoc_1:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: float_ip_1 }
      port_id: { get_resource: float_port_1 }

  host1:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: Ubuntu
          params:
            lastname: { get_param: last_name }
      image: Ubuntu 16.04
      flavor: cy.medium
      diskConfig: AUTO
      networks: 
        - port: { get_resource: float_port_1 }
      user_data: 
        str_replace:
          template: |
            #!/bin/bash  
            export DEBIAN_FRONTEND=noninteractive
            echo 127.0.0.1 $(hostname) >> /etc/hosts
            apt-get -y update
            pkg_array=({locate,dnsutils,lsof,aptitude,ftp,auditd,xinetd,telnetd,samba,git,zip,unzip,figlet,sshpass,hexedit,hexeditor,tree,apache2,gcc,tcc,build-essential,libreadline-dev,libssl-dev,libpq5,libpq-dev,libreadline5,libsqlite3-dev,libpcap-dev,git-core,autoconf,postgresql,pgadmin3,curl,zlib1g-dev,libxml2-dev,libxslt1-dev,libyaml-dev,nmap,python-setuptools,python-dev,hydra,hydra-gtk,john,xrdp,netcat,firefox,figlet,lolcat,ubuntu_desktop})
            apt-get -y upgrade
            for x in ${pkg_array[@]}; do apt-get install -y $x; done
            apt-get -y install qemu && apt-get -y install qemu
            gem install lolcat
            updatedb
            mandb
            mkdir /usr/share/class
            
            # ----- GRABS PE BINARIES <ENSURE URL IS CURRENT>
            wget -r -l 1 -nH -nd -R "index.html*","*.gif","*.pyc","banner.*" 10.50.20.181/linux/ -P /usr/share/class/
            wget 10.50.20.181/linux/check.pyc -O /usr/share/misc/check.pyc
            wget 10.50.20.181/linux/banner.sh -O /usr/share/misc/banner.sh
            cat > /usr/share/misc/check_script.sh << "__EOF__"
            #!/bin/bash
            /usr/bin/env python /usr/share/misc/check.pyc
            __EOF__
            echo 'alias check="/usr/share/misc/check_script.sh"' >> /etc/bash.bashrc
            chmod +x /usr/share/class/*
            chmod +x /usr/share/misc/{check.pyc,banner.sh,check_script.sh}
            
            # ----- ENABLES SSH
            sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
            sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
            systemctl restart ssh
            
            # ----- ENABLES TELNET
            cat > /etc/xinetd.d/telnet <<"__TELNET__"
            # default: on
            # description: The telnet server serves telnet sessions; it uses
            # unencrypted username/password pairs for authentication.
            service telnet
            {
            disable = no
            flags = REUSE
            socket_type = stream
            wait = no
            user = root
            server = /usr/sbin/in.telnetd
            log_on_failure += USERID
            }
            __TELNET__
            for x in {0..9}; do echo "pts/$x" >> /etc/securetty ; done
            systemctl restart xinetd.service
            
            # ----- INSTALLS LOGGING RULES INTO /etc/rsyslog.conf <not default in UBUNTU>
            cat > /tmp/log_rules.txt <<"__LOGS__"
            
            ###############
            #### RULES ####
            ###############
            #
            # First some standard log files.  Log by facility.
            #
            auth,authpriv.*			/var/log/auth.log
            *.*;auth,authpriv.none	-/var/log/syslog
            #cron.*				    /var/log/cron.log
            daemon.*			    -/var/log/daemon.log
            kern.*				    -/var/log/kern.log
            lpr.*				    -/var/log/lpr.log
            mail.*				    -/var/log/mail.log
            user.*				    -/var/log/user.log
            
            __LOGS__
            sed '/$IncludeConfig \/etc\/rsyslog.d\/\*.conf/r /tmp/log_rules.txt' -i /etc/rsyslog.conf
            systemctl restart rsyslog.service
            
            useradd $user -m -U -s /bin/bash
            useradd -m zeus -U -s /bin/bash
            usermod -aG sudo $user
            usermod -aG sudo zeus
            echo "root:$password" | chpasswd
            echo "$user:$password" | chpasswd
            echo "zeus:PassWord1234" | chpasswd
            
            # ----- EXPLOITATION TOOLS INSTALL
            easy_install pip
            pip install pefile capstone
            git clone https://github.com/g0tmi1k/exe2hex.git /usr/share/exe2hex
            git clone https://github.com/1aN0rmus/TekDefense-Automater.git /usr/share/automater
            git clone https://github.com/secretsquirrel/the-backdoor-factory.git /usr/share/backdoor
            git clone https://github.com/Veil-Framework/Veil.git /usr/share/veil
            /usr/share/Veil/setup/setup.sh -c
            git clone https://github.com/danielmiessler/SecLists.git /usr/share/seclists
            systemctl reboot
          params:
            $user: { get_param: last_name }
            $password: { get_param: password }
            $studentID: { get_param: student_id }
      user_data_format: RAW
  
  float_ip_2:
    type: OS::Neutron::FloatingIP
    depends_on: stu-router
    properties: { floating_network: public }

  float_port_2:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: stu-network }
      fixed_ips:
        - subnet_id: { get_resource: stu-subnet }
          ip_address:
            str_replace:
              template: 10.studentID.0.2
              params:
                studentID: { get_param: student_id }
      port_security_enabled: false
  
  float_ip_assoc_2:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: float_ip_2 }
      port_id: { get_resource: float_port_2 }
  
  host2:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: Debian
          params:
            lastname: { get_param: last_name }
      image: Debian Jessie
      flavor: cy.medium
      diskConfig: AUTO
      networks: 
        - port: { get_resource: float_port_2 }
      user_data: 
        str_replace:
          template: |
            #!/bin/bash            
            echo 127.0.0.1 $(hostname) >> /etc/hosts
            export DEBIAN_FRONTEND=noninteractive
            apt-get -y update
            pkg_array=({locate,dnsutils,lsof,aptitude,ftp,auditd,xinetd,telnetd,samba,git,zip,unzip,figlet,sshpass,hexedit,hexeditor,tree,apache2,gcc,tcc,build-essential,libreadline-dev,libssl-dev,libpq5,libpq-dev,libreadline5,libsqlite3-dev,libpcap-dev,git-core,autoconf,postgresql,pgadmin3,curl,zlib1g-dev,libxml2-dev,libxslt1-dev,libyaml-dev,nmap,python-setuptools,python-dev,hydra,hydra-gtk,john,xrdp,netcat,firefox,lolcat,LXDE})
            apt-get -y upgrade
            for x in ${pkg_array[@]}; do apt-get install -y $x; done
            apt-get -y install qemu && apt-get -y install qemu
            gem install lolcat
            updatedb
            mandb
            mkdir /usr/share/class
            
            # ----- GRABS PE BINARIES <ENSURE URL IS CURRENT>
            wget -r -l 1 -nH -nd -R "index.html*","*.gif","*.pyc","banner.*" 10.50.20.181/linux/ -P /usr/share/class/
            wget 10.50.20.181/linux/check.pyc -O /usr/share/misc/check.pyc
            wget 10.50.20.181/linux/banner.sh -O /usr/share/misc/banner.sh
            cat > /usr/share/misc/check_script.sh << "__EOF__"
            #!/bin/bash
            /usr/bin/env python /usr/share/misc/check.pyc
            __EOF__
            echo 'alias check="/usr/share/misc/check_script.sh"' >> /etc/bash.bashrc
            chmod +x /usr/share/class/*
            chmod +x /usr/share/misc/{check.pyc,banner.sh,check_script.sh}
            
            # ----- ENABLES SSH
            sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
            sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
            sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config
            systemctl restart ssh
            
            # ----- ENABLES TELNET
            cat > /etc/xinetd.d/telnet <<"__EOL__"
            # default: on
            # description: The telnet server serves telnet sessions; it uses
            # unencrypted username/password pairs for authentication.
            service telnet
            {
            disable = no
            flags = REUSE
            socket_type = stream
            wait = no
            user = root
            server = /usr/sbin/in.telnetd
            log_on_failure += USERID
            }
            __EOL__
            for x in {0..9}; do echo "pts/$x" >> /etc/securetty ; done
            systemctl restart xinetd.service
            
            useradd -m -U -s /bin/bash $user 
            useradd -m -U -s /bin/bash zeus
            usermod -aG sudo $user
            usermod -aG sudo zeus
            echo "root:$password" | chpasswd
            echo "$user:$password" | chpasswd
            echo "zeus:PassWord1234" | chpasswd
            
            # ----- EXPLOITATION TOOLS INSTALL
            easy_install pip
            pip install pefile capstone
            git clone https://github.com/g0tmi1k/exe2hex.git /usr/share/exe2hex
            git clone https://github.com/1aN0rmus/TekDefense-Automater.git /usr/share/automater
            git clone https://github.com/secretsquirrel/the-backdoor-factory.git /usr/share/backdoor
            git clone https://github.com/Veil-Framework/Veil.git /usr/share/veil
            /usr/share/Veil/setup/setup.sh -c
            git clone https://github.com/danielmiessler/SecLists.git /usr/share/seclists
            systemctl reboot
          params:
            $user: { get_param: last_name }
            $password: { get_param: password }
            $studentID: { get_param: student_id }
      user_data_format: RAW
  
  float_ip_3:
    type: OS::Neutron::FloatingIP
    depends_on: stu-router
    properties: { floating_network: public }

  float_port_3:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: stu-network }
      fixed_ips:
        - subnet_id: { get_resource: stu-subnet }
          ip_address:
            str_replace:
              template: 10.studentID.0.3
              params:
                studentID: { get_param: student_id }
      port_security_enabled: false
  
  float_ip_assoc_3:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: float_ip_3 }
      port_id: { get_resource: float_port_3 }
  
  host3:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: SAMBA Target
          params:
            lastname: { get_param: last_name }
      image: Windows 7
      flavor: cy.large
      diskConfig: AUTO
      networks: 
        - port: { get_resource: float_port_3 }
      user_data: 
        str_replace:
          template: |
            #ps1_sysnative
            $ErrorActionPreference = 'SilentlyContinue'
            netsh advfirewall set allprofiles state off
            # set-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -name "dontdisplaylastusername" -Value 1
            
            # ----- DISABLE PASSWORD COMPLEXITY REQUIREMENT
            secedit /export /cfg c:\secpol.cfg
            (gc C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File C:\secpol.cfg
            (gc C:\secpol.cfg).replace("MinimumPasswordLength = 7", "MinimumPasswordLength = 1") | Out-File C:\secpol.cfg
            (gc C:\secpol.cfg).replace("SeInteractiveLogonRight = *S-1-5-32-544,*S-1-5-32-548,*S-1-5-32-549,*S-1-5-32-550,*S-1-5-32-551,*S-1-5-9", "SeInteractiveLogonRight = *S-1-5-32-544,*S-1-5-32-548,*S-1-5-32-549,*S-1-5-32-550,*S-1-5-32-551,*S-1-5-9,*S-1-1-0,*S-1-5-11") | Out-File C:\secpol.cfg
            secedit /configure /db c:\windows\security\local.sdb /cfg c:\secpol.cfg
            rm -force c:\secpol.cfg -confirm:$false
            
            # ----- INSTRUCTOR NEEDS TO LOGIN AS ONE OR MORE USERS TO DEMO MIMIKATZ
            net user /add Bill DoDC0mPL1antPassW0rd!! /y
            net localgroup administrators /add Bill
            net user /add Susan Susan+Cats /y
            net user /add Robert PassWord123 /y
            net user /add Jacob UberL0ngPassw0rd /y
            net user /add Eeyore hatemyjob /y
            net user /add Ian password /y
            net localgroup administrators /add Eeyore
            net user /add $user $password /y
            
            Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
            
            # ----- UNINSTALLS KBs FOR EXPLOITATION
            Invoke-WebRequest -Uri "10.50.20.181/linux/KB.ps1" -OutFile "C:\KB.ps1"
            (new-object Net.WebClient).DownloadFile( "http://10.50.20.181/linux/KB.ps1", "C:\KB.ps1" )
            Invoke-WebRequest -Uri "10.50.20.181/windows/.hidden/TTW/PsExec.exe" -OutFile "C:\PsExec.exe"
            (new-object Net.WebClient).DownloadFile( "http://10.50.20.181/windows/.hidden/TTW/PsExec.exe", "C:\PsExec.exe" )
            Set-ItemProperty "HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce" -name "KB" 'C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe -noprofile -sta -File "C:\KB.ps1"'
            New-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update" -Name AUOptions -Value 1 -PropertyType Dword | Out-Null
            get-service wuauserv | stop-service -Force
            C:\PsExec.exe -accepteula -u Bill -p DoDC0mPL1antPassW0rd!! \\$(hostname) cmd /c "exit" -accepteula -nobanner
            C:\PsExec.exe -accepteula -u Eeyore -p hatemyjob \\$(hostname) cmd /c "exit" -accepteula -nobanner
            exit 1001
            shutdown -r -f
          params:
            $user: { get_param: last_name }
            $password: { get_param: password }
            $studentID: { get_param: student_id }
      user_data_format: RAW