== DEV/TCP Connect Demo

{empty} +

*Learning Objectives / Outcomes*

** 2.1 Describe active methods used for network discovery

** 5.11 Perform server identification

** 10.4 Explain the reverse file transfer process with netcat

** 10.5 Demonstrate the process for transferring files via terminal

{empty} +

== Demo Walk-through

{empty} +

_Netcat is a utility that is generally used to read of write information from network connections. Because of the many ways that this utility can be exploited by adversaries, it is highly 
recommend that it be removed from production servers. That being said, given access to a machine, even without netcat installed, you can use the principles upon
which it operates to transfer information, interact with application or port scan (just like you can do with netcat!)_

{empty} +

*Follow the below steps*

{empty} +

=== File Transfer with /dev/tcp

{empty} + 

 
1) Log into H3. You can make yourself root, or use sudo as invoke the command.

2) You will establish a listening port on H3 and receive the contents of the file you created on H1 into the socket. Use the command: "nc -l -p 1111 > file.txt"

4) Now go to H1 and create a file that you will send to H3. Make sure to write a message you will recognize into the file.

5) Use the command: "cat file.txt > /dev/tcp/10.2.0.4/1111" to send the file from H1 to H3

5) You can go back to H3 and check the contents of the file.txt that you connected to the listener, it should display the file contents you sent from H1.

{empty} +

=== Custom Interactions with /dev/tcp

{empty} + 

 
1) Log into H1. You can make yourself root, or use sudo as invoke the command.

2) Create the following bash script on the machine to pull the webpage from H3:

{empty} +

----

#!/bin/bash

exec 3<>/dev/tcp/10.2.0.4/80

echo -e "GET /index.html HTTP/1.1\r\nhost: 10.2.0.4\r\nConnection: close\r\n\r\n" >&3

cat <&3

----

{empty} +

3) Simply run the script, and you should be presented with the webpage from H3.

{empty} +

=== Custom Port Scanner with /dev/tcp

{empty} + 

1) Log into H1. You can make yourself root, or use sudo as invoke the command.

2) Create the following bash script on the machine to scan ports 20 thru 80 (you can do more/different ports but for our environment, this saves time) and saves the results to a file in your home directory:

{empty} +

----

#!/bin/bash

let p=20

while [ $p -lt 80 ];

do echo > /dev/tcp/10.2.0.4/$p;

  if [ $? == 0 ]; then
  
    echo $p "is open" >> /home/lastname/scan.txt; 
    
  fi;
  
let p=(p+1)

done

----

{empty} +

3) Simply run the script and check the file called "scan.txt" created in your home directory. This shows the ports that were open when scanned.

{empty} +
 


