:doctype: book
:stylesheet: ../../cctc.css

= Activity - File Permissions and ACLS
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Learning Objectives / Outcomes

[square]
* Objective 3.2 - Describe file system ownership properties
* Objective 3.2.2 - Identify user and group owner.
* Objective 3.2.3 - Understand how linux user groups work.
* Objective 3.3 - Discuss file system permissions.
* Objective 3.3.1 - Identify file permissions from ls output.
* Objective 3.3.2 - Use chmod to change permissions.

{empty} +

== Scenario

_Welcome to the Galactic Empire Messaging System!_ One of our servers recently failed and we are in the process of rebuilding our message board. We managed to salvage all the messages, which are just a series of plaintext files kept in a flat directory structure. Furthermore, we know who our users were but we need to recreate all of their accounts and reset file permissions identical to the way they were, _lest we incur the Emperor's wrath._

{empty} +

== Activity

Given the attributes below, recreate the users, groups, and messages/files, and assign applicable permissions, ACLs, and attributes for each:

_2 User Groups:_
[width="15%"]
|===
|Name       |GUID
|`rebels`   |`2000`
|`imps`     | `2100`
|===

_2 ACLs:_
[width="20%"]
|===
|GUID   |Access Permissions
|`2000` |`rwx`
|`2100` |`rwx`
|===

_4 Users:_
[width="50%"]
|===
|Name           |UID    |Real Name          |Office
|`smuggla4lyfe` |`2010` |`han.solo`         |`corellia`
|`notacommittee`|`2011` |`leia.organa`      |`alderaan`
|`dachosen1`    |`2110` |`anakin.skywalker` |`tatooine`
|`ultimatepowah`|`2111` |`sheev.palpatine`  |`naboo`
|===

_Files/messages:_ +
`rebels_only`           is owned by leia, & the rebels, is rwx-able by the owner, and all rebels but no one else. +
`imps_only`		        is owned by palpatine, and the imps, is rwx-able by the owner, rx-able by all imps, and has no further permissions. +
`rebel_scum!`           is owned by anakin, and the imps, is rwx-able by the owner, and is read-only by everyone else. +
Hint: Should 'everyone else' include the group? +
`imps_are_bad`          is owned by `nobody`, and the rebels, readable by the owner, rwx-able by the rebels group, and is read-only by others. +
`rebel_base_location`   is owned by sheev, and the imps, and is fully accessible(rwx) by the imps group. +
`deathstar_plans`       is owned by Leia, and the rebels, and is fully accessible(rwx) by the rebels group. +

{empty} +

== Deliverables

* Once you have completed all the required tasks above, run the following command from the working directory to get the flag: `$ check` +
* Verification of check script success

{empty} +

== Hints

* From working directory: `$ ls -l | awk '{print $1, $3, $4, $9}' | column -t`

{empty} +

== Challenge

NONE

{empty} +

== Useful Resources

NONE
