:doctype: book
:stylesheet: ../../cctc.css

= Activity - Raw Socket Programming
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Learning Objectives / Outcomes
[square]
* Skill 1: Identify Networking Fundamentals
* Objective 1.1 Understanding the OSI model and Basic Networking
* Objective 1.3 Explain the difference between user space/kernel space sockets
* Objective 1.4 Tool and OS feature operations
* SKILL 2: Identify the sections of common packet headers
* Objective 2.2 Describe IPv4 and IPv6 packet structures


{empty} +

== Scenario

You have control (sudo privileges) on a Linux client (10.1.0.2) in an IPv4 network. You need to get a message to 10.1.0.1. You don't have tools installed, and installing new tools or libraries would trigger an alarm. The host has Python installed however so you must use this to achieve your goal.  You can use the socket, sys and one additional module of your choice. 

{empty} +

== Activity

=== Task 1) 

.Using a python script, you will create a raw socket and code your message into the socket. This must be sent to the host at 10.1.0.1. You can verify success by using wireshark while you send the message on either the H1 or target host.

{empty} +

1) You can retrieve a shell of the script at: https://git.cybbh.space/CCTC/public/raw/master/networking/additional_resources/RAWSOCK.py

2) Fill in all the areas with “?”. Read the Comments carefully!

3) You may also build your own script from scratch or make modifications to the script provided if you have python experience.

4) After you have made your changes to the script (or created your own), ensure you have  permission to execute it. Bring up Wireshark to view the packet and execute the script. You can use "python RAWSOCK.py" to execute.

{empty} +

== Deliverables
[square]

* Document your steps to fill in the script.
* Screenshot showing successful communications between your Linux client and the message target at 10.1.0.1.
* Screenshot showing how (and validating) that the message was somehow obfuscated for transmission.

{empty} + 

