:doctype: book
:stylesheet: ../../cctc.css

= Activity - Raw Socket Programming
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Learning Objectives / Outcomes
[square]
* Skill 1: Identify Networking Fundamentals
* Objective 1.1 Understanding the OSI model and Basic Networking
* Objective 1.3 Explain the difference between user space/kernel space sockets
* Objective 1.4 Tool and OS feature operations
* SKILL 2: Identify the sections of common packet headers
* Objective 2.2 Describe IPv4 and IPv6 packet structures


{empty} +

== Scenario

.You have control (sudo privileges) on a Linux client (10.1.0.2) in an IPv4 network. You need to get a message to 10.1.0.1. You don't have tools installed, and installing new tools or libraries would trigger an alarm. The host has Python 2.7 installed, so you can use this to achieve your goal.  You can use the socket, sys and one additional module of your choice. 
.Using a python script, you will create a raw socket and code your message into the socket. This must be sent to the host at 10.1.0.1. You can verify success by using wireshark while you send the message on either the H1 or target host.
{empty} +

== Activity

=== Task 1) 
*Information gathering*

1) First you will need to collect the information you will need in order to create a packet. The IP Header field info will need to be in decimal format; ensure you understand what should be represented within each field from a binary perspective, then convert this information to decimal.

2) Next you should have the IP Header field size that will contain the information. You will need this in order to properly store the variables assigned with the values identified in step 1 into a structure.

3) Lastly, get information about the python modules you are going to use. You know you will use socket and sys. You should also try to find a module you can use to help encode the information to obfuscate it. The following are references for the socket and sys modules: 

* https://docs.python.org/2/library/socket.html

* https://docs.python.org/2/library/sys.html

{empty} +

=== Task 2)
*Start your script*

1) Start by using the following reference to create a raw socket with error handleing:

* https://docs.python.org/2/tutorial/errors.html

* The below snippet is an example of how to so this can be done. The snippet is not functional however; the CAPITALIZED items would need to be filled out appropriately. Reference the socket module to figure out what these values should be.

----
try:
    s = socket.FUNCTION(socket.FAMILY, socket.TYPE, socket.PROTOCOL)
except socket.error as msg:
    print 'Socket creation failed!. Error Code : ' + str(msg[0]) + ' Message ' + msg[1]
    sys.exit()
----

2) Next you will need to create a packet with an IP header and a message. This will require a number of variables. You can use the following, or create your own list, as long as it can be arranged into a structure appropriately. See the following refernce on how to pack data into structures:

* https://docs.python.org/2/library/struct.html

_Ensure you use "network" or big-endian for your byte order._

* The snippet below is not funtional, but demonstrates how to initiate the packet, set data into the IP header fields, and shows an incomplete line for using the pack function.

----
packet = '';

# IP Header fields
source_ip = 'x.x.x.x'
dest_ip = 'x.x.x.x'	
ip_ver_ihl = ?
ip_tos = ?	    
ip_len = 0      
ip_id = ?       
ip_frag = ?	   
ip_ttl = ?   
ip_proto = ?
ip_check = 0
ip_saddr = socket.inet_aton ( source_ip )
ip_daddr = socket.inet_aton ( dest_ip )
# Packing the feilds into a structure
ip_header = pack('!????????????' , ip_ver_ihl, ip_tos, ip_len, ip_id, ip_frag, ip_ttl, ip_proto, ip_check, ip_saddr, ip_daddr)
----

3) You will need to create user data to insert into the packet (after the IP header) as well. This data will need to be encoded. You can use a module of your choice to achieve this, however a good place to start maybe the binascii module.

4) The last part of the script will be creating your packet and sending your packet using the raw socket you have created.

* The snippet below is not funtional, but demonstrates how to assemble the packet and send it.

----
packet = ip_header + user_data_variable
 
s.FUNCTION(packet, (dest_ip , 0 ))
----

{empty} +

=== Task 3)
*Send your packet*

1) You should have wireshark running when you send the packet so that you can verify that work script works.

{empty} +

=== Task 4)
*Check your results*

1) You can retrieve a shell of the script at: https://git.cybbh.space/CCTC/public/raw/master/networking/additional_resources/RAWSOCK.py

2) Fill in all the areas with “?”. Read the Comments carefully!

3) After you have made your changes to the script, ensure you have  permission to execute it. Bring up wireshark to view the packet and execute the script. You can use "python RAWSOCK.py" to execute.

4) Were the results comparable to the script you created in Task 1-3?  If not, what was different?  

{empty} +

== Deliverables
[square]

* Document your steps to fill in the script.
* Screenshot showing successful communications between your Linux client and the message target at 10.1.0.1.
* Screenshot showing how (and validating) that the message was somehow obfuscated for transmission.

{empty} + 

