:doctype: book
:stylesheet: ../../cctc.css

== Learning Objectives / Outcomes

- SKILL CCNE009: Configure filtering devices

= Activity - Firewall Configuration

{empty} +

== Scenario

Your organization needs access to a DMZ that was recently added. There is a pfsense firewall is attached to (2) trusted LANs and a DMZ. The DMZ should not be allowed to make unsolicited connections into the trusted networks. 

*Before you start this activity*, you will need to log into the pfsense machine and *disable the default allow rules to the Lan, Lan2, and DMZ interfaces*. You can find the IP addresses on your network diagram in the main networking directory of blackboard. 

*USERNAME: admin*

*PASSWORD: password*


{empty} +

== Activity

Task 1) 

1. Allow traffic from the net1 host destined to the DMZ host TCP port 1234. 

2. Explicitly Block and log traffic from the net1 host destined to the DMZ host TCP port 7777. All other ports should still be blocked by the implicit deny rule.

3. Explicitly allow the net1 host destined to net3 host via HTTP. All other ports should still be blocked by the implicit deny rule.

4. Explicitly allow the net1 host destined to access the DMZ host via SSH.

*Test your rules *

{empty} +

Task 2)

1. Acting as a insider, you have access to *ONLY* the net1 host. You need to provide access to the web server located on the net3 host to the DMZ host in order to stage information for exfiltration. *Use tunneling commands you learned during your SSH tunneling section to complete this task*

2. A network administrator has discovered the misconfiguration in the firewall. Acting as the network administrator perform the necessary firewall configurations to prevent future incidents and further harden the firewall device.

{empty} +

== Deliverables

* You will be expected to be reproduce your process and explain what each rule is doing based on direction and the goal.


{empty} +

== References

* https://www.netgate.com/docs/pfsense/config/example-basic-configuration.html

