:doctype: book
:stylesheet: ../../cctc.css

== Learning Objectives / Outcomes

- SKILL CCNE009: Configure filtering devices

= Activity - Firewall Configuration

{empty} +

== Scenario

Your organization needs access to a DMZ that was recently added. There is a pfsense firewall is attached to (2) trusted LANs and a DMZ. The DMZ should not be allowed to make unsolicited connections into the trusted networks.

{empty} +

== Activity

Task 1) 

1. Allow tcp port 1234 destined to the DMZ host from net1. 

2. Explicitly Block and log traffic destined for tcp port 7777 from net1 to the DMZ host. All other ports should still be blocked by the implicit deny rule.

3. Explicitly allow the net1 host to access the web page hosted by net3. All other ports should still be blocked by the implicit deny rule.

4. Explicitly allow the net1 host to access the DMZ host via SSH.

*Test your rules *

{empty} +

Task 2)

1. Acting as a insider, you have access to the net1 host. You need to provide access to the web server located on the net3 host to the DMZ client in order to stage information for exfiltration. *Use tunneling commands you learned during your SSH tunneling section to complete this task*

2. A network administrator has discovered the misconfiguration in the firewall. Acting as the network administrator perform the necessary firewall configurations to prevent future incidents and further harden the firewall device.

{empty} +

== Deliverables

* You will be expected to be reproduce your process and explain what each rule is doing based on direction and the goal.


{empty} +



