:doctype: book
:stylesheet: ../../cctc.css

= Activity - IPTables for Filtering
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Learning Objectives / Outcomes

* Skill/Objective NUM - List objectives here

{empty} +

== Scenario

If there is a story or scenario, present it here.

{empty} +

== Activity

Overall description of the activity.

=== Task 1)

1. The H1 client should be allowed to initiate new telnet and SSH connections. H1 should also allow connections outbound to tcp/udp ports 1234, 9001, 9002, 1111, 2222 and 9050. Established communications should also be allowed to ensure communications are successful.


2. The H3 client should be allowed to initiate new SSH, HTTP,  and TCP 9001-9002 connections. Established communications should also be allowed to ensure communications are successful.


3. Both H1 and H3 clients should never allow traffic to/from TCP/UDP ports 7777 and 9999.


4. Deny ping (ICMP) operations on H1 and H3 hosts. (Remember ping is a two part transaction. You should be thorough and filter both parts)


5. Ensure your Policy for the INPUT, OUTPUT and FORWARD tables default policy is ACCEPT.


5. Test Condition:  Attempt to SSH between the H1 and H3 Clients (you can use non-standard ports also to verify rules such as 9999 or 7777 to test the DROP rules). Ensure your IPTables rules are enforcing the above requirements.


{empty} +

== Deliverables

* List any deliverables here

{empty} +

== Hints

* List hints here (if any)

{empty} +

== Challenge

1. Change the TTL on H3 from 64 to 128.

2. Apply IPTables to mitigate SYN Floods.

3. Apply logging to the Rule from Task 1 that drops ping/ICMP traffic on H1. Verify that you can see the messages in the /var/logs/messages that should be created by initiating a ping on the H1.

{empty} +

== Useful Resources

* List any documents, videos, tutorials, or links that could be helpful with the activity here