:doctype: book
:stylesheet: ../../cctc.css

= Activity - IPTables for Filtering

== Learning Objectives

* CCNE007.013 - Construct IPTable rules

== Learning Outcomes

* N/A

== Scenario

* You will be constructing and placing IPTables rules to meet the intent for filtering on the Linux hosts as specified.

=== Task 1)

. The Net1 client should be allowed to initiate new telnet and SSH connections. Net1 should also allow connections outbound to tcp/udp ports 1234, 9001, 9002, 1111, 2222 and 9050. Established communications should also be allowed to ensure communications are successful.
. The Net3 client should be allowed to initiate new SSH, HTTP,  and TCP 9001-9002 connections. Established communications should also be allowed to ensure communications are successful.
. Both Net1 and Net3 clients should never allow traffic to/from TCP/UDP ports 7777 and 9999.
. Deny ping (ICMP) operations on Net1 and Net3 hosts. (Remember ping is a two part transaction. You should be thorough and filter both parts)
. Ensure your Policy for the INPUT, OUTPUT, and FORWARD tables default policy is DROP.
. Test Condition:  Attempt to SSH between the Net1 and Net3 Clients (you can use non-standard ports such as 9999 or 7777 to test and verify the DROP rules). Ensure your IPTables rules are enforcing the above requirements.

== Deliverables

* Document the rules and process you used to construct the IPTables rules.
* Test the rules to confirm they meet the intent of the activity.

== Hints

* The "-m" flag is an extension that helps to define matches of a list of more specific criteria, such as "states" and "multiport".

== Challenge

. Change the TTL on Net3 from 64 to 128.
. Apply IPTables to mitigate SYN Floods. (Try testing with nmap)
. Apply logging to the rule created from Task 1 that drops ping/ICMP traffic on Net1. Verify that you can see the messages located in "/var/logs/messages"  file that should be created by initiating a ping on the Net1 client.
. Utilize bpf bytecode to block icmp traffic with "deadbeef" in the payload. (You must flush your current table rules)

== Useful Resources

* http://ipset.netfilter.org/iptables.man.html
* http://ipset.netfilter.org/iptables-extensions.man.html