:doctype: book
:stylesheet: ../cctc.css

= Activity 1- File Transfers
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
// Uncomment next line to set page size (default is Letter)
//:pdf-page-size: A4

== Learning Objectives / Outcomes
[square]
* Skill 10: Perform file transfers
* Objective 10.1- Describe common methods for transferring files 
* Objective 10.2- Describe covert methods for transferring files
* Objective 10.3- Explain the forward file transfer process with netcat
* Objective 10.5- Demonstrate the process for transferring files via terminal

{empty} +

== Activity

For this exercise you will continue using your individual topology but *BEFORE YOU START*, ensure that you remove *all filtering rules*, and configure a permit any rule for the pfsense firewall on the LAN and OPT interfaces.  In this activity, you will use various file transfer methods between the H1 client and the H3 client. In later exercises.

{empty} +


=== Task 1)

You need to send SCP1 from H1 > H3 received as SCP3

* Create "SCP1.txt" on the H1 client and write "SCP Transfer" into the file.

* Use SCP to transfer SCP1 from H1 to H3. Name the file "SCP3.txt" on the H3 side.

{empty} +


=== Task 2)

You need to send NETCAT3 from H3 > H1 received as NETCAT1

* Create "NETCAT3.txt" on the H3 client and write "NETCAT Transfer" into the file.

* Use NETCAT to transfer NETCAT3 from H3 to H1. Name the file "NETCAT1.txt" on the H1 side.

{empty} +


=== Task 3)

You need to send SOCAT1 from H1 > H3 received as SOCAT3

* Create "SOCAT1.txt" on the H1 client and write "SOCAT Transfer" into the file.

* Use SOCAT to transfer SOCAT1 from H1 to H3. Name the file "SOCAT3.txt" on the H3 side.

{empty} +


== Deliverables
[square]
* Ensure after each transfer that the new file contents were received with the message appropriate to the transfer you are conducting.
* Document the syntax for the transfers and any issues you may have had (and how you resolved them).

{empty} +


